import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Toaster } from "@/components/ui/sonner"
import { Analytics } from "@/components/analytics"

import { cn } from "@/lib/utils"

export const metadata: Metadata = {
  title: "Holdings",
  // description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-background min-h-svh overscroll-none font-sans antialiased",
          GeistSans.variable,
        )}
      >
        {children}
        <Toaster position="top-center" />
        <Analytics />
      </body>
    </html>
  );
}
